### ISSUE TITLE
No servers configured

### ISSUE THREAD

**Issue by migozz** [simonrob/email-oauth2-proxy#148] opened 2023-03-26 16:45 UTC
I'm on default config, and it says "No servers configured", and no ports opened for listening.
But the accounts are present.
I'm on Windows 7 and using Python 3.8.10.
I'm using generated binaries.
And it doesn't close on "Quit", and probably doesn't reload config on "Reload config".

Sorry, it's because I'm used a Windowed, not a Console.
And, for Console, I will always have a "black window"?

**Comment by simonrob** [comment] 2023-03-26 20:00
Based on your other issues it seems like you have resolved this, but if not, please could you provide more detail, and the configuration file you are using? Note that configuration files should be placed in the same directory as the executable (or provided via `--config-file`).

**Comment by migozz** [comment] 2023-03-26 21:08
It works only when complied as Console, but there's always a black Console window opened.
When compiled as GUI, then there's no console and not working.
The config is correctly located, because Accounts are present, but no Servers.
The config file is default.

**Comment by simonrob** [comment] 2023-03-28 19:47
I've now found the root cause of this – once [this PR](https://github.com/r0x0r/pywebview/pull/1086) is merged into a pywebview release the Windows PyInstaller `--onefile` builds of the proxy will work again.

In the meantime, if you want to create an executable, you can do it via: `python -m PyInstaller --noconsole --onefile --hidden-import timeago.locales.en_short emailproxy.py`.

**Closed** 2023-05-02 21:05 UTC
