### ISSUE TITLE
mail client

### ISSUE THREAD

**Issue by dzeigenfuss** [simonrob/email-oauth2-proxy#129] opened 2023-01-31 00:53 UTC
Using a Limilabs.client and the email auth2 prox is listening for auth requests, but not intercepting authentication requests and there are no pending authorization requests to approve. Any suggestions are greatly appreciated! Thank You!

**Comment by dzeigenfuss** [comment] 2023-01-31 13:36
[emailproxy.log](https://github.com/simonrob/email-oauth2-proxy/files/10546826/emailproxy.log)

Thanks for the reply back. Attached is the log. It does not appear to have much to it

**Comment by simonrob** [comment] 2023-01-31 20:05
There is no evidence in this log of your client actually connecting to the proxy. My guess is that you have not correctly set up `localhost` on port `995` as the email server in your client.

If you definitely have already done this, I would suggest changing the port used by the proxy to, say, `1995` (as in the example configuration) just in case the issue is being caused by the proxy not being allowed to open port `995` and for some reason not being able to detect this (ports below 1024 are normally marked as privileged).

**Comment by dzeigenfuss** [comment] 2023-02-01 00:05
Thanks for the response back. Unfortunately, I am dealing with more of a service, than a client. The service allows me to define mail accounts in a gui format for authenticating O365 mailboxes to pull in mail items.  On the defined mail account, I have also reverted back to using port 1995, but still unable to connect with the proxy. Probably because I am using a s/w vendor defined email receiver service and not necessarily a client.  All though it does utilize a Limilabs client through a mail.dll.

**Comment by simonrob** [comment] 2023-02-01 06:51
It shouldn't make any difference what the end application is as long as it uses IMAP, POP or SMTP. But you certainly do need to be able to set the server host name as well as its port. I'd recommend getting support from the developer of the service you are using if you're still not able to get it set up.

I'm going to close this issue for now as it is not a problem with the proxy and I don't think there's anything else I can suggest.

**Closed** 2023-02-01 06:51 UTC
