### ISSUE TITLE
Can't athenticate -window doesn't appear

### ISSUE THREAD

**Issue by matthewgeier** [simonrob/email-oauth2-proxy#248] opened 2024-05-08 22:14 UTC
Client connects to proxy - _ get the popup requesting to authorise. I assume I should get a window to interact with Oauth, but no window appears and the following appears on the console -

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pystray/_base.py", line 324, in inner
    callback(self)
  File "/usr/lib/python3/dist-packages/pystray/_base.py", line 449, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/*****/email-oauth2-proxy/emailproxy.py", line 2812, in authorise_account
    self.create_authorisation_window(request)
  File "/*****/email-oauth2-proxy/emailproxy.py", line 2842, in create_authorisation_window
    authorisation_window.loaded += self.authorisation_window_loaded
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'loaded'

I assume this error is preventing a 'browser' window from appearing to do the interactive part of the login.

Ubuntu 24.04. I MAY be missing a python dependency.

**Comment by simonrob** [comment] 2024-05-09 08:22
Thanks for reporting, but please take a look at existing issues before opening a new one. This is a duplicate of #242.

**Closed by simonrob** 2024-05-09 08:22 UTC
