### ISSUE TITLE
Storing OAuth token in secrets manager?

### ISSUE THREAD

**Issue by michaelstepner** [simonrob/email-oauth2-proxy#33] opened 2022-06-14 04:05 UTC
I'm opening this issue to inquire whether you would be open to merging a PR that implements an option to store the OAuth token in a Secrets Manager (e.g. AWS Secrets Manager, Github Secrets or Terraform Cloud Workspace Variables) instead of the local config. This would facilitate managing OAuth authorization and token creation from a local computer, while making the token seamlessly available to a remote server running `email-oauth2-proxy`. It would also facilitate persisting the token if the remote server needs to be destroyed and recreated.

As mentioned in a prior issue, I've been working on an infrastructure-as-code project which uses Terraform to automatically configure an AWS server running `email-oauth2-proxy`. I've just made a first version of my work public at: [michaelstepner/email-oauth2-proxy-aws](https://github.com/michaelstepner/email-oauth2-proxy-aws).

As you might anticipate, the biggest limitation of my automated server configuration is authenticating with the email provider to obtain OAuth tokens. Thanks to your prior work, after creating the lightweight server I'm able to authenticate manually via SSH using `--no-gui` and `--local-server-auth`. But I would love to configure a more elegant solution someday.

I wouldn't ask you to implement this yourself, of course, unless you were interested in doing so.

## Implementation

I considered a command-line argument, but I'm currently envisioning a per-account configuration option like `token_store` below:

```
[your.office365.address@example.com]
permission_url = https://login.microsoftonline.com/common/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/common/oauth2/v2.0/token
oauth2_scope = https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
redirect_uri = http://localhost
client_id = *** your client id here ***
client_secret = *** your client secret here ***
token_store = aws_secrets_manager
```

If that configuration option were left unspecified, it would default to `local` and the behaviour would follow the status quo, storing the token in the config file. This would preserve backward compatibility, and maintain simplicity for the majority of users who are using this software as a local client in their system tray.

Additional configuration required for the secrets manager could either be via environment variables (e.g. credentials for access to the secrets manager) or the configuration file.

**Comment by michaelstepner** [comment] 2022-06-14 14:57
Thanks for your thoughtful and thorough reply! I'll respond in-line:

> My key concern before merging would be about overcomplicating the proxy – I'm quite keen to keep it as simple and focused as reasonably possible, so if it's a straightforward change to add this capability then I'd be open to it, but if it would end up drawing in lots more dependencies and adding lots of extra complexity then I'd be less keen.

I think the extra dependencies and complication would be minimal.

* Dependencies: For example, to use AWS Secrets Manager would bring in a dependency on `boto3`.
* Code complications: I think changes would be limited to `OAuth2Helper.get_oauth2_credentials`. In my quick skim, it seems this function is solely responsible for fetching and storing the OAuth2 token. Adding the option for a secrets manager would mean fetching and storing from a difference source.

> How would you actually store the four required OAuth values? (`access_token`, `access_token_expiry`, `refresh_token` and `token_salt`). The set of valid email address characters doesn't match the set of permitted key name characters in the secrets managers I looked at, so you'd need some sort of mapping here (or an additional value in the configuration file).

One possible design would be to store all tokens in a valid JSON string, like:

```json
{
   "email1@example.com":{
      "access_token":"QWERYUIOP",
      "access_token_expiry":1234567890,
      "refresh_token":"ASDFGHJKL",
      "token_salt":"ZXCVBNM"
   },
   "email2@example.com":{
      "access_token":"QWERYUIOP",
      "access_token_expiry":1234567890,
      "refresh_token":"ASDFGHJKL",
      "token_salt":"ZXCVBNM"
   }
}
```

The key for the secret could either be:
* hardcoded
* optionally configurable on an application-wide basis
    * via an env variable, or
    * via a config option within [Server setup]

> I'm also interested in how you'd surface the token request to the user. I agree that being able to manage this remotely without needing to ssh into a server and authenticate is a benefit, but what would the interaction flow look like from the client's point of view? Would they have to manually generate and process the authentication request?

I was thinking that a user could install `email-oauth2-proxy` locally and remotely, configuring both to use the same secrets store. Then if you successfully authenticate locally, the tokens are stored in the secret store and immediately available to the remote server.

I think this idea was inspired by [rclone authorize](https://rclone.org/commands/rclone_authorize/), which I've used in my work.

> As it happens, I was recently thinking about how to achieve this with a plugin (not yet committed, but see the [plugins branch](https://github.com/simonrob/email-oauth2-proxy/tree/plugins) for the basic capabilities) – essentially it could trigger an email to the account when there is an authentication request, and then intercept an email reply from the user with the updated authentication response in the body. This is a little similar to how Gmail allows security alert emails to be retrieved via IMAP even when everything else is blocked because of that security alert. Of course, this is a bit of a hack, but it makes the user side very easy, which is I think an important factor.

This is really clever, I love this idea. I think it would be complementary to a secrets manager, since the secrets manager would still facilitate persisting the tokens across multiple servers (ex: a local and remote server, or re-creating the remote server without re-authenticating). However, it might entirely obviate the need for a secrets manager, since re-authenticating a remote server would become much less of a hassle.

**Comment by billbliss** [comment] 2022-06-30 18:27
Between something like this and the POP branch, this sounds like exactly what I was looking for. GMail still hasn't implemented OAuth2 for GMail POP3 and I'm about to lose access to my personal O365 tenant email because Microsoft is deprecating basic auth.

I was hoping to deploy `email-oauth2-proxy` as an Azure Function/AWS Lambda but that would require a place to store the OAuth values, and a secrets manager is what I was thinking for that, but I hadn't thought about the implications and reading this thread I would have seriously underestimated them!

All that being said, I realized I may have jumped to a conclusion - how is `email-oauth2-proxy` designed to be/typically deployed? Maybe it's simpler to use a laptop or a Raspberry Pi or something and have it run locally.

**Comment by simonrob** [comment] 2022-07-01 07:33
The proxy was initially designed for my own personal use on a desktop/laptop because I was going to lose access to O365 through a client I would find it difficult to do without. As a result it is GUI-first, with a menu bar icon and interactive authentication screen. For this reason (and the other challenges discussed earlier in this issue thread) it could be quite painful to use a secrets manager effectively. So, yes, if you're able to use the proxy locally that may well be simpler.

Do you have a typo in your comment – "GMail still hasn't implemented OAuth2 for GMail POP3"? Gmail definitely does support OAuth for POP3, so perhaps you meant a specific client here? Regardless, the POP branch will almost certainly be merged once I've had chance to complete the implementation, so you should have full support via the proxy.

**Comment by michaelstepner** [comment] 2022-07-01 16:48
@billbliss You may wish to check out my work at [michaelstepner/email-oauth2-proxy-aws](https://github.com/michaelstepner/email-oauth2-proxy-aws). I built upon @simonrob's wonderful work on making a local client and deployed it to an EC2 instance for my use case: I wanted to provide access to O365 to my favourite cloud email provider which had not implemented OAuth2.

You were hoping to use a serverless framework like Azure Functions or AWS Lambda. That would indeed would be cheaper, but struck me as very difficult to implement for SMTP since it is not an HTTP-based API. I therefore used the cheapest AWS instance available to set up a server, and the final cost for me is around US$4 per month (no guarantees as to your costs, of course).

I've fully documented the [installation steps in the README of michaelstepner/email-oauth2-proxy-aws](https://github.com/michaelstepner/email-oauth2-proxy-aws#installation), and it's 100% functional for me. Adding a feature to store credentials in a secrets manager would streamline the installation and quarterly config refresh, but if you're willing to tolerate a bit of manual config via SSH, I think my installation guide would get you up and running.

**Comment by billbliss** [comment] 2022-07-05 16:14
Sweet! I will take a look. A quarterly SSH isn’t too bad. Spaced on the “those protocols aren’t http” but obviously too. Thx!

**Comment by simonrob** [comment] 2022-07-12 06:51
Another option here could just be to synchronise the config file between instances of the proxy. You'd get the benefits of shared credentials but the proxy changes required would be far more minor.

**Comment by simonrob** [comment] 2022-12-05 18:07
Excellent! Thanks for the work on this - great to see you found an approach with minimal impact to the proxy's core features. Let me know how you get on; happy to review fully after that with a view to merging.

**Comment by michaelstepner** [comment] 2022-12-19 06:07
Reopening this issue now that I've tested my implementation of this feature and opened PR #114.

@simonrob I welcome your feedback and you should feel free to request changes from me or directly edit the proposed changeset!

**Comment by thiagomacieira** [comment] 2023-01-19 20:22
Would it not be better to first have the tool store its state (the access tokens) somewhere other than the config file?

Right now, I need to  make the config file writable to the tool while it runs, which is sub-optimal. Ideally, the tool should run with systemd's [`ProtectSystem=full`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectSystem=) or `strict`, which make the `/etc` dir read-only but allow `/var` to remain writable.

**Comment by simonrob** [comment] 2023-01-20 15:57
Separating configuration and caching has been requested before, but I don't personally have the need for it or the spare time to implement it I'm afraid.

I'll happily review a PR (or maybe accept sponsorship to add this), but it will need careful integration with the various existing features. Probably the simplest approach is to modify the load/save methods of the AppConfig class.

**Comment by michaelstepner** [comment] 2023-01-21 18:00
@thiagomacieira if you decide to pursue this further, I think the code in PR #114 (which is close to being merged) provides a good template for what changes are required to store the tokens elsewhere.

In fact, PR #114 does meet your objective of storing the access tokens somewhere other than the config file...but with the dependency on AWS Secrets Manager, whereas it sounds like you'd like to store them in a separate local file.

The other question raised would be where to store the `lastactivity` state. In PR #114, that remains stored in the local config, which remains writable (and written to) by the proxy. But it sounds like you'd want that separated out too.

**Comment by simonrob** [comment] 2023-01-31 08:43
@thiagomacieira it turns out that generalising #114 made supporting a local cache file much more straightforward, so this is now available in that PR. The exact configuration may change between now and merging, but it would be useful if you could test that feature.

**Comment by thiagomacieira** [comment] 2023-01-31 15:14
Thanks, let me take a look!

**Comment by thiagomacieira** [comment] 2023-02-06 06:59
The change looks good from reading. I'll test it soon too.

**Comment by thiagomacieira** [comment] 2023-02-06 16:18
Confirmed, working just fine. The config file is now owned by root and is actually world-readable; the auth cache file is read-write, but only writable by the user running emailproxy.py.

I'll make a PR with the systemd service file I'm using.

**Closed** 2023-03-09 20:46 UTC
