### ISSUE TITLE
Compiling with --noconsole option causes crash

### ISSUE THREAD

**Issue by bwbug** [simonrob/email-oauth2-proxy#134] opened 2023-02-08 02:27 UTC
I used the [installation instructions](https://github.com/simonrob/email-oauth2-proxy#dependencies-and-setup) for creating a self-contained executable using `pyinstaller`, and confirmed that this works.  However, the executable runs in a console, and closing the console window unfortunately also eliminates the systray icon.  Unfortunately, closing the console is easy to do by accident, and in addition, the console creates a taskbar button that takes up valuable space in the taskbar.

I've attempted to compile an executable that does not have a console, using the `--noconsole` option, as follows:

`pyinstaller --noconsole --onefile emailproxy.py --hidden-import timeago.locales.en`

However, running the resulting executable produces the following run-time error:

![image](https://user-images.githubusercontent.com/109386143/217412469-70d167d5-b979-44e3-86a2-400a43dd6e4b.png)

The full text of the error message is shown below.

```
Traceback (most recent call last):
  File "emailproxy.py", line 74, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "webview\__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "webview\http.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'
```
&nbsp;
Is there any way to run the proxy (in Windows 10) without the console?

**Comment by simonrob** [comment] 2023-02-08 19:29
Thanks for reporting this. I can replicate the issue, but it is related to [this change](https://github.com/pyinstaller/pyinstaller/issues/3503) in PyInstaller 5.7.0, and is caused by pywebview not the proxy. There is an explanation of the reason in [this issue](https://github.com/kivy/kivy/issues/8074) on a different project. In summary, PyInstaller has changed the way that `stdout` and `stderr` are handled in `--noconsole` mode on Windows. I added a bit of context to an existing pywebview issue; hopefully this can be resolved.

In the meantime, downgrade your version of PyInstaller to fix this: `python -m pip install pyinstaller==5.6.2` (or use `--no-gui` mode in the proxy).

---

> I also tried `pythonw emailproxy.py` but this failed silently (no systray icon).

Where are you running that `pythonw` command from? For me, Command Prompt works fine, but in PowerShell I need to redirect/suppress the output streams (e.g., `pythonw emailproxypy *>$null`).

Incidentally, if you use the proxy's `Start at Login` option it will generate a single file in `shell:startup` that you can click to launch the proxy if that is what you're primarily looking for here.

**Comment by simonrob** [comment] 2023-02-08 20:49
Yes, `--no-gui` suppresses the systray icon, hence why it also fixes this GUI-related issue. Downgrading PyInstaller will achieve what you want here – it may not be a viable option forever, but I suspect the core issue will be fixed via pywebview well before that becomes a problem.

**Comment by simonrob** [comment] 2023-02-09 09:30
Pywebview's author has already proposed a [fix](https://github.com/r0x0r/pywebview/tree/logwriter-bottle) for this – please could you test by installing the branch via `python3.7 -m pip install https://github.com/r0x0r/pywebview/archive/logwriter-bottle.zip` and let me know whether this resolves the issue?

**Comment by simonrob** [comment] 2023-02-20 17:19
I recently reported a related issue to pywebview and proposed a [fix](https://github.com/r0x0r/pywebview/pull/1048) that has now been merged (see the [pywebview report](https://github.com/r0x0r/pywebview/issues/1044) for details).

I will leave this issue open until it is possible to pin a specific released version of pywebview in the proxy's requirements, but until then it can be resolved by force installing the fixed version: `python -m pip install git+https://github.com/r0x0r/pywebview.git`

**Closed** 2023-02-23 08:38 UTC
