### ISSUE TITLE
Authorization screen blank

### ISSUE THREAD

**Issue by Thijs-TvP** [simonrob/email-oauth2-proxy#8] opened 2021-11-17 17:24 UTC
Hi Simon,

When using the script on a windows 10 pro pc the authorization screen is empty/blank.
![Authorization-empty](https://user-images.githubusercontent.com/94557976/142250612-6908bf95-1be1-4834-a4e7-621ab7bd9275.png)

Regards,
Thijs

**Comment by simonrob** [comment] 2021-11-17 20:49
Thanks for reporting this. Does the same thing happen in both authorisation modes? (i.e., is the behaviour different whether `External authorisation mode` is selected or not?)

Please could you also let me know what web engine your version of pywebview is using? You can do this by running [this script](https://github.com/simonrob/email-oauth2-proxy/files/7557867/pywebview-web-engine.py.zip). When you do so, please: 1) let me know whether you see a website in the popup window or just a blank page; and, 2) copy and paste the script's output here for me.

**Comment by Thijs-TvP** [comment] 2021-11-18 09:59
Hi Simon,

Thanks for the quick reply.

It happens in both authorisation modes.

I ran the script, it also gives an blank/empty screen (like the screenshot above).
The output of the script is;

C:\email-oauth2-proxy-main>python3 pywebview-web-engine.py
<module 'webview.platforms.winforms' from 'C:\\Users\\*******\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\webview\\platforms\\winforms.py'>

**Comment by simonrob** [comment] 2021-11-18 13:27
This issue was was resolved via email (to allow sharing private logs).

The root cause was a version mismatch between Python 3.10 and PythonNET (for which at the time of writing there is no Python 3.10 compatible version). The solution was to downgrade to Python 3.9.x and use the matching [prebuilt wheel](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet).

**Closed by simonrob** 2021-11-18 13:27 UTC
